name: thread_clone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  device_preview: ^1.2.0
  faker: ^2.1.0
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  gallery_saver: ^2.3.2
  go_router: 6.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
